/// Message types supported in the chat system
///
/// This enum defines all possible message types that can be sent
/// in conversations between clients and suppliers.
///
/// The message types support various use cases:
/// - Basic communication (text, image, file)
/// - Business operations (quote, booking)
/// - System notifications (system)
enum MessageType {
  /// Plain text message
  ///
  /// Used for standard text-based communication between users.
  /// This is the most common message type.
  text,

  /// Image message
  ///
  /// Contains a reference to an uploaded image file.
  /// Can optionally include caption text.
  image,

  /// File attachment message
  ///
  /// Contains a reference to an uploaded file (PDF, documents, etc).
  /// Includes both file URL and filename for proper display.
  file,

  /// Quote/proposal message
  ///
  /// Sent by suppliers to clients with pricing and package details.
  /// Contains structured quote data including price, package info,
  /// validity period, and terms.
  quote,

  /// Booking reference message
  ///
  /// References an existing booking in the system.
  /// Used to discuss or share booking details in a conversation.
  /// Contains booking ID and basic booking information.
  booking,

  /// System-generated message
  ///
  /// Automated messages generated by the system for notifications
  /// or status updates. Cannot be sent directly by users.
  /// Examples: "Booking confirmed", "User joined conversation"
  system,
}

/// Extension methods for MessageType enum
extension MessageTypeExtension on MessageType {
  /// Returns a human-readable string representation of the message type
  String get displayName {
    switch (this) {
      case MessageType.text:
        return 'Text Message';
      case MessageType.image:
        return 'Image';
      case MessageType.file:
        return 'File';
      case MessageType.quote:
        return 'Quote';
      case MessageType.booking:
        return 'Booking';
      case MessageType.system:
        return 'System Message';
    }
  }

  /// Returns true if this message type requires media content
  bool get requiresMedia {
    return this == MessageType.image || this == MessageType.file;
  }

  /// Returns true if this message type requires structured data
  bool get requiresStructuredData {
    return this == MessageType.quote || this == MessageType.booking;
  }

  /// Returns true if this message type can be sent by users
  bool get canBeSentByUser {
    return this != MessageType.system;
  }
}
