// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIsAMA5W5oeSs7gxbdciIWJnkC0dRqHgs',
    appId: '1:801918014868:android:92f3f10cfbc09af7306b81',
    messagingSenderId: '801918014868',
    projectId: 'boda-connect-49eb9',
    storageBucket: 'boda-connect-49eb9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA86ggLaUAfPcZHT8UGRptNTECi75Gqic4',
    appId: '1:801918014868:ios:89b1b70e24b523ae306b81',
    messagingSenderId: '801918014868',
    projectId: 'boda-connect-49eb9',
    storageBucket: 'boda-connect-49eb9.firebasestorage.app',
    iosBundleId: 'bodaconnect.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsAMA5W5oeSs7gxbdciIWJnkC0dRqHgs',
    appId: '1:801918014868:web:ddd61c7943f7e19b306b81',
    messagingSenderId: '801918014868',
    projectId: 'boda-connect-49eb9',
    authDomain: 'boda-connect-49eb9.firebaseapp.com',
    storageBucket: 'boda-connect-49eb9.firebasestorage.app',
  );
}
